# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

# シェルのプロンプトの間に空行を挿入する
add_newline = true

# 記号"❯"を記号"➜"に置き換える
[character] # 編集するモジュールの名前は"character"
success_symbol = "[➜](bold green)" # "success_symbol"を記号"➜"で"bold green"(太字の緑色)にセット
error_symbol = "[➜](bold red)"    #コマンド失敗時
# パッケージモジュールを無効化することでプロンプトを完全に非表示にする
[package]
disabled = true

[directory]
# ディレクトリ表示
truncation_length = 10
truncate_to_repo = false

[time]
# 時間の表示をオンにして12時間表示に
disabled = false
